all:
        hosts:
                
                gateway:
                        ansible_host: 10.0.0.254
                        ansible_ssh_user: itesciadmin

                dns:
                        ansible_host: 10.0.0.102
                        ansible_ssh_user: itesciadmin

                backup:
                        ansible_host: 10.0.0.101
                        ansible_ssh_user: itesciadmin

                web-server:
                        ansible_host: 10.0.0.103
                        ansible_ssh_user: itesciadmin

                mail:
                        ansible_host: 10.0.0.104
                        ansible_ssh_user: itesciadmin

