---
- hosts: all
  become: true

  tasks:
  - name: "Add the user"
    user:
      name: "{{ item.name }}"
    with_items:
       - { name: itescia }
       - { name: toto }
       - { name: riadhadmin}  

  - name: "Deploy package "
    package:
      name: "{{ item.package }}"
      state: present
    with_items: 
       - { package: vim }
       - { package: htop }
         
