---
- hosts: all
  become: true
  vars: 
        users: [itescia, toto, riadhadmin]
        package: [htop, vim ]
  tasks:
  - name: "Add the user"
    user:
      name: "{{ item }}"
    with_items: "{{ users }}"

  - name: "Deploy package "
    package:
      name: "{{ item }}"
      state: present
    with_items: "{{ package }}"

  - name: "Key ssh"
    authorized_key:
       user: "{{ item }}"
       key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
       exclusive: true
    with_items: "{{ users }}"
         
